### ISSUE TITLE
Breaking up the API

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/apidoc#6]
I know this is a very young project and breaking it up already seems excessive but after discussing the lack of need for precise geometry storage in the first phases of this project the following idea emerged:

> What if we break up the API into smaller services that will better scale to user's use patterns

The idea above is mainly that people will first input a large amount of geometry, then run simulation and then run post-processing on results. Furthermore the objects covered in this project are a mix of Honeybee and Ladybug objects but what happens when we want to add Butterfly, Dragonfly and maybe even Spider? This repository will then become enormous, unweildly and will create massive containers than are more likely to fail.

As such I propose we break up this repo into the following end points:
* Geometry: manages surfaces, surface states and models (collections of geometry objects)
* Grids: manages daylighting grids, their window groups and daylighting results (not sure about the last one)
* Recipes: manages recipes and potentially workflow templates in the future (not just run DF but maybe run LEED compliant sim)
* Jobs/Simulations: manages running simulations, holds their state as well as coordinates sub-tasks (eg: large building simulation == multiple smaller grid simulations)
* Sky: manages sky objects
* Weather: manages EPWs and WEAs

As demonstrated [here](https://medium.com/@somakdas/code-repository-for-micro-services-mono-repository-or-multiple-repositories-d9ad6a8f6e0e) this break up can be done in 2 ways: 
1. 1 repo per end point
2. a mega repo but each folder is a self contained end point so they can all be tested/deployed seperately

Any thoughts on this @mostaphaRoudsari or @chriswmackey? Feel free to tag in whoever else you might think has an opinion on this issue.

I'll leave you with a final post on the `why` of [microservice design](https://koukia.ca/a-microservices-implementation-journey-part-1-9f6471fe917).

**Comment by mostaphaRoudsari** [comment]
This issue was for ladybug-tools-api repository which is now removed. I wanted to keep a copy of the issue and hence transferred it here.
